spring:
  application:
    name: control-panel
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /control-panel

logging:
  level:
    root: INFO

environments:
  test:
    scripts:
      update: /opt/control-panel/scripts/update_test.sh
      start: /opt/control-panel/scripts/start_test.sh
      stop: /opt/control-panel/scripts/stop_test.sh
      restart: /opt/control-panel/scripts/restart_test.sh
      status: /opt/control-panel/scripts/status_test.sh
    health-url: https://dekanat.ntu.edu.ua/test/actuator/health
