spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://db-prod:3306/control_panel_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    esvar.ua.dekanatcontrolpanel: INFO
