server:
  port: 8080
  servlet:
    context-path: /control-panel

spring:
  datasource:
    url: jdbc:mysql://db-prod:3306/control_panel_db?useSSL=false&serverTimezone=UTC
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    ua.ntu.controlpanel: INFO
