spring:
  application:
    name: control-panel
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /control-panel

logging:
  level:
    root: INFO
