server:
  port: 8099
  servlet:
    context-path: /control-panel

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_panel_db?useSSL=false&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    ua.ntu.controlpanel: DEBUG
